import { ReactNode } from 'react';

//import { Header } from '@/features/header/header';
import { Header } from '@/components/Header';
import { Footer } from '@/features/footer/footer';
import { routing } from '@/i18n/routing';
import { cn } from '@/lib/utils';
import { AuthenticationProvider } from '@/providers/AuthenticationProvider';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'sonner';

import '../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;

  setRequestLocale(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={cn(geistSans.variable, geistMono.variable, 'min-h-screen bg-background')}>
        <NextIntlClientProvider>
          <AuthenticationProvider>
            <div className='relative flex min-h-screen flex-col'>
              <Header />
              <main className='flex-1'>
                {children}
                <Toaster richColors position='top-right' />
              </main>
              <Footer />
            </div>
          </AuthenticationProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
